# Chapter 4 — Semantic Search from Scratch

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hamzafarooq/advanced-rag-from-scratch/blob/main/colab_original_notebooks/Chapter_4.ipynb)

This notebook accompanies **Chapter 4** of *Build an Advanced RAG Application (From Scratch)*.

We start with a corpus of hotel reviews and build a semantic search engine in three increasingly fast forms:

1. **Pure NumPy** — cosine similarity by hand.
2. **NumPy with normalized Euclidean distance** — same ranking, different metric.
3. **FAISS** — the production-grade vector search library.

We finish by comparing FAISS index types (Flat / HNSW / IVF-PQ) on the same query.

## 1. Setup

In [ ]:
from IPython.display import HTML, display

def set_css(*args, **kwargs):
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', set_css)

In [ ]:
#download the required libraries

!pip install huggingface
!pip install -U datasets
#!pip install sentence-transformers
!pip install faiss-cpu
!pip install einops
!pip install sentence_transformers

Collecting huggingface
  Downloading huggingface-0.0.1-py3-none-any.whl.metadata (2.9 kB)
Downloading huggingface-0.0.1-py3-none-any.whl (2.5 kB)
Installing collected packages: huggingface
Successfully installed huggingface-0.0.1

In [ ]:
import pandas as pd
from datasets import load_dataset
import numpy as np
from sentence_transformers import SentenceTransformer
import torch
import scipy.spatial
from datasets import load_dataset



dataset = load_dataset("traversaal-ai-hackathon/hotel_datasets")

## 2. Load the Paris hotel reviews

The dataset is hosted on the HuggingFace Hub. The first call downloads it; subsequent calls hit the local cache.

In [ ]:
df=pd.DataFrame(dataset['train'])
df.head()

,hotel_name,hotel_description,review_title,review_text,rate,tripdate,hotel_url,hotel_image,price_range,rating_value,review_count,street_address,locality,country
0,Romance Istanbul Hotel,Romance Istanbul Hotel has 39 rooms.Every room...,"An exceptional boutique hotel, great value for...",None,NaN,February 2020,https://www.tripadvisor.com/Hotel_Review-g2939...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,5.0,4023,Hudavendigar Cd. No:5 Sirkeci,Istanbul,Turkiye
1,Romance Istanbul Hotel,Romance Istanbul Hotel has 39 rooms.Every room...,You can’t get better than this.,None,NaN,March 2021,https://www.tripadvisor.com/Hotel_Review-g2939...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,5.0,4023,Hudavendigar Cd. No:5 Sirkeci,Istanbul,Turkiye
2,Romance Istanbul Hotel,Romance Istanbul Hotel has 39 rooms.Every room...,Exceeds all expectations,None,NaN,March 2021,https://www.tripadvisor.com/Hotel_Review-g2939...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,5.0,4023,Hudavendigar Cd. No:5 Sirkeci,Istanbul,Turkiye
3,Romance Istanbul Hotel,Romance Istanbul Hotel has 39 rooms.Every room...,"Great Location, Fantastic Accommodations",None,NaN,August 2021,https://www.tripadvisor.com/Hotel_Review-g2939...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,5.0,4023,Hudavendigar Cd. No:5 Sirkeci,Istanbul,Turkiye
4,Romance Istanbul Hotel,Romance Istanbul Hotel has 39 rooms.Every room...,Perfection. It is all in the details.,None,NaN,June 2021,https://www.tripadvisor.com/Hotel_Review-g2939...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,5.0,4023,Hudavendigar Cd. No:5 Sirkeci,Istanbul,Turkiye

In [ ]:
df_paris = df.loc[df.locality=='Paris']

In [ ]:
df_paris.to_csv('df_paris.csv', index=False)

In [ ]:
df_paris.head()

,hotel_name,hotel_description,review_title,review_text,rate,tripdate,hotel_url,hotel_image,price_range,rating_value,review_count,street_address,locality,country
4797,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,Awesome Paris Hotel!,"Fantastic hotel! Awesome location, great chara...",5.0,January 2024,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
4798,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,Charming Hotel,Charming Hotel in a central location. The sta...,5.0,May 2023,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
4799,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,Highly recommend this hotel,Highly recommend this hotel and we would absol...,5.0,December 2023,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
4800,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,"Good location, excellent staff and large room",Good central location - close to Metro and man...,5.0,December 2023,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
4801,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,"Good staff, quiet and beautiful location.","Lovely staff. All were good, and Manon was out...",5.0,January 2024,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France

In [ ]:
df_paris.hotel_name.value_counts()

hotel_name
Hotel Malte - Astotel                  40
Hotel Astoria - Astotel                40
Novotel Paris Les Halles               40
La Maison Favart                       40
Grand Hotel du Palais Royal            40
Hotel Maison Mere                      40
Hotel des Arts - Montmartre            40
Hotel Joke - Astotel                   40
Passy Eiffel Hotel                     40
Best Western Plus La Demeure           40
Hotel 34B - Astotel                    40
Hotel La Comtesse                      40
Cler Hotel                             40
Hotel Marignan Champs-Elysees          40
Hotel Piapia                           40
Hotel Moliere                          40
citizenM Paris Champs-Elysees          40
Hotel du Danube Saint Germain          40
Hotel B55                              40
Hotel Europe Saint Severin             40
Citadines Tour Eiffel Paris            40
Pullman Paris Eiffel Tower Hotel       40
Hotel Tourisme Avenue                  40
Grand Hotel Malher                     40
The People - Paris Belleville          40
Hotel Square Louvois                   40
Hotel du Printemps                     40
St Christopher's Inn Canal Paris       40
St Christopher's Gare du Nord Paris    40
Hotel Campanile Paris Bercy Village    40
Name: count, dtype: int64

In [ ]:
df_paris.drop_duplicates()

,hotel_name,hotel_description,review_title,review_text,rate,tripdate,hotel_url,hotel_image,price_range,rating_value,review_count,street_address,locality,country
4797,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,Awesome Paris Hotel!,"Fantastic hotel! Awesome location, great chara...",5.0,January 2024,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
4798,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,Charming Hotel,Charming Hotel in a central location. The sta...,5.0,May 2023,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
4799,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,Highly recommend this hotel,Highly recommend this hotel and we would absol...,5.0,December 2023,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
4800,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,"Good location, excellent staff and large room",Good central location - close to Metro and man...,5.0,December 2023,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
4801,Hotel Malte - Astotel,Located in the 2nd district next to the Stock ...,"Good staff, quiet and beautiful location.","Lovely staff. All were good, and Manon was out...",5.0,January 2024,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$$ (Based on Average Nightly Rates for a Stand...,5.0,2985,63 rue de Richelieu,Paris,France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5992,Hotel Campanile Paris Bercy Village,"In the east of Paris, the hotel Campanile Berc...",Nice hotel but had trouble booking in.,We had just had a very long and delayed train ...,3.0,September 2019,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,4.0,1625,17 rue Baron le Roy,Paris,France
5993,Hotel Campanile Paris Bercy Village,"In the east of Paris, the hotel Campanile Berc...",Great Location,We stayed at the Kyriad Hotel Paris Bercy Vill...,4.0,September 2019,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,4.0,1625,17 rue Baron le Roy,Paris,France
5994,Hotel Campanile Paris Bercy Village,"In the east of Paris, the hotel Campanile Berc...",Great location,Stayed here for a few days and it is a great l...,5.0,October 2019,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,4.0,1625,17 rue Baron le Roy,Paris,France
5995,Hotel Campanile Paris Bercy Village,"In the east of Paris, the hotel Campanile Berc...",For one night only,We stayed here for one night on our way to Ita...,3.0,September 2019,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,4.0,1625,17 rue Baron le Roy,Paris,France
5996,Hotel Campanile Paris Bercy Village,"In the east of Paris, the hotel Campanile Berc...",Nice hotel in Paris Bercy,The Hotel is close to the metro station Cour S...,4.0,September 2019,https://www.tripadvisor.com/Hotel_Review-g1871...,https://media-cdn.tripadvisor.com/media/photo-...,$ (Based on Average Nightly Rates for a Standa...,4.0,1625,17 rue Baron le Roy,Paris,France

## 3. Embed the reviews

We use `nomic-ai/nomic-embed-text-v1.5` — a strong open-weight 768-dim embedding model. On CPU this takes a few minutes; on GPU it's much faster.

In [ ]:
model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5",trust_remote_code=True)

In [ ]:
if torch.cuda.is_available(): #A
    model = model.to('cuda')
    print("CUDA is available. The model has been moved to GPU.")
else:
    print("CUDA is not available. The model will run on CPU.")

CUDA is available. The model has been moved to GPU.

In [ ]:
reviews = df_paris['review_text'].tolist()

In [ ]:
review_embeddings = model.encode(reviews, show_progress_bar=True)#A

In [ ]:
print(f"Embeddings shape: {review_embeddings.shape}")

Embeddings shape: (1200, 768)

In [ ]:
# Define cosine-based semantic search over the embedding matrix.

import numpy as np

def cosine_search(query_embedding, review_embeddings, k):
    # Reshape the query embedding to have a shape of (768,)
    query_embedding = query_embedding.reshape(-1)

    # Compute the dot product between the query embedding and all review embeddings
    dot_products = np.dot(review_embeddings, query_embedding)

    # Compute the L2 norms of the query embedding and review embeddings
    query_norm = np.linalg.norm(query_embedding)
    review_norms = np.linalg.norm(review_embeddings, axis=1)

    # Compute the cosine similarity scores
    cosine_similarities = dot_products / (query_norm * review_norms)

    # Get the indices of the top-k highest cosine similarity scores
    top_indices = np.argsort(-cosine_similarities)[:k]

    # Get the cosine similarity scores of the top-k similar reviews
    top_cosine_similarities = cosine_similarities[top_indices]

    return top_indices, top_cosine_similarities

In [ ]:
# Define Euclidean search on normalized vectors for comparison.

import numpy as np

def euclidean_search(query_embedding, review_embeddings, k):
    # Reshape the query embedding to have a shape of (768,)
    query_embedding = query_embedding.reshape(-1)

    # Normalize the query embedding and review embeddings
    query_embedding_normalized = query_embedding / np.linalg.norm(query_embedding)
    review_embeddings_normalized = review_embeddings / np.linalg.norm(review_embeddings, axis=1, keepdims=True)

    # Compute the Euclidean distances between the normalized query embedding and normalized review embeddings
    distances = np.linalg.norm(review_embeddings_normalized - query_embedding_normalized, axis=1)

    # Get the indices of the top-k smallest distances
    top_indices = np.argsort(distances)[:k]

    # Get the distances of the top-k similar reviews
    top_distances = distances[top_indices]

    return top_indices, top_distances

## 4. Search by hand: cosine similarity

No libraries needed. We compute dot products of L2-normalized vectors.

In [ ]:
query = "Hotel with a view of the Eiffel tower."

In [ ]:
# Embed the query and retrieve the top matches with cosine similarity.

import time
query_embedding = model.encode([query])#.astype('float32')

k = 5  # Number of similar reviews to retrieve

start_time = time.time()


indices, distances = cosine_search(query_embedding, review_embeddings, k)

biencoder_search_time = time.time() - start_time
print(f"Bi-encoder search time: {biencoder_search_time:.4f} seconds")

#indices, distances = euclidean_search(query_embedding, review_embeddings, k)

Bi-encoder search time: 0.0020 seconds

In [ ]:
print(f"Query: {query}")
print("Top hotel with similar reviews:")
for i, (idx, distance) in enumerate(zip(indices, distances), 1):
    print(f"{i}. {df_paris.iloc[idx]['hotel_name']}")
    print(f"Review: {df_paris.iloc[idx]['review_text']}")
    print(f"Distance: {distance:.4f}")
    print()

Query: Hotel with a view of the Eiffel tower.
Top hotel with similar reviews:
1. Pullman Paris Eiffel Tower Hotel
Review: Excellent service. Stunning view of the Eiffel towere from our balcony, The room is gorgeous, comfortable and spacious. Definitely will be recommending this hotel to family and friends. If you’re looking for a hotel that has everything you need in Paris, luxury and view, this is the one.
Distance: 0.8227

2. Pullman Paris Eiffel Tower Hotel
Review: If you stay at this hotel it is for the amazing views of the Eiffel Tower and for the pictures.  The photos and memories of being on the balcony looking at the Eiffel Tower in all its splendor cannot be denied.   When we arrived we were impressed with proximity of hotel to the Eiffel Tower. Definitely within walking distance, 7 minutes, we could even see our hotel when we climbed up the tower later that day . The view itself is spectacular!! We were upgraded to a suite top floor (9th floor) with a balcony. My kids had a seperate room , the view with no balcony, twin beds. They loved the view. That was an experience of a lifetime.   Breakfast was good. I did feel it was overpriced for what you get, cereal, fruit, eggs, different teas, water. But the selection was enormous and
Distance: 0.8078

3. Citadines Tour Eiffel Paris
Review: Had a Eiffel tower balcony view room and the view did not disappoint was absolutely amazing and so nice to see everyone from the room or balcony. Staff at reception were nice and was no problem in checking out 1 hour later for free. Very clean hotel.
Distance: 0.7935

4. Hotel Marignan Champs-Elysees
Review: Very good hotel near the Champs-Elysees.  The superior rooms are very nice and a good size.  The Eiffel Tower suite has an excellent view of the Eiffel Tower. Within walking distance of many things but far enough away from the Champs to feel like you are not right in the middle of a tourist spot.  The thing that makes this hotel is the staff.  They are helpful and willing to do anything they can to make your stay perfect.
Distance: 0.7929

5. Hotel Tourisme Avenue
Review: Nice Hotel only a few minutes away from Eiffel tower. 3 Metro lines in Front of the hotel, supermarket and restaurants very close. Small but nice and clean rooms, good bed, very friendly and helpful personal, very good breakfast buffet.
Distance: 0.7914

## 5. Same ranking via normalized Euclidean distance

For unit-norm vectors, `||a − b||² = 2(1 − cos(a, b))`, so Euclidean distance ranks identically to cosine similarity (just inverted).

In [ ]:
indices, distances = euclidean_search(query_embedding, review_embeddings, k)

In [ ]:
print(f"Query: {query}")
print("Top hotel with similar reviews:")
for i, (idx, distance) in enumerate(zip(indices, distances), 1):
    print(f"{i}. {df_paris.iloc[idx]['hotel_name']}")
    print(f"Review: {df_paris.iloc[idx]['review_text']}")
    print(f"Distance: {distance:.4f}")
    print()

Query: Hotel with a view of the Eiffel tower.
Top hotel with similar reviews:
1. Pullman Paris Eiffel Tower Hotel
Review: Excellent service. Stunning view of the Eiffel towere from our balcony, The room is gorgeous, comfortable and spacious. Definitely will be recommending this hotel to family and friends. If you’re looking for a hotel that has everything you need in Paris, luxury and view, this is the one.
Distance: 0.5955

2. Pullman Paris Eiffel Tower Hotel
Review: If you stay at this hotel it is for the amazing views of the Eiffel Tower and for the pictures.  The photos and memories of being on the balcony looking at the Eiffel Tower in all its splendor cannot be denied.   When we arrived we were impressed with proximity of hotel to the Eiffel Tower. Definitely within walking distance, 7 minutes, we could even see our hotel when we climbed up the tower later that day . The view itself is spectacular!! We were upgraded to a suite top floor (9th floor) with a balcony. My kids had a seperate room , the view with no balcony, twin beds. They loved the view. That was an experience of a lifetime.   Breakfast was good. I did feel it was overpriced for what you get, cereal, fruit, eggs, different teas, water. But the selection was enormous and
Distance: 0.6200

3. Citadines Tour Eiffel Paris
Review: Had a Eiffel tower balcony view room and the view did not disappoint was absolutely amazing and so nice to see everyone from the room or balcony. Staff at reception were nice and was no problem in checking out 1 hour later for free. Very clean hotel.
Distance: 0.6426

4. Hotel Marignan Champs-Elysees
Review: Very good hotel near the Champs-Elysees.  The superior rooms are very nice and a good size.  The Eiffel Tower suite has an excellent view of the Eiffel Tower. Within walking distance of many things but far enough away from the Champs to feel like you are not right in the middle of a tourist spot.  The thing that makes this hotel is the staff.  They are helpful and willing to do anything they can to make your stay perfect.
Distance: 0.6435

5. Hotel Tourisme Avenue
Review: Nice Hotel only a few minutes away from Eiffel tower. 3 Metro lines in Front of the hotel, supermarket and restaurants very close. Small but nice and clean rooms, good bed, very friendly and helpful personal, very good breakfast buffet.
Distance: 0.6459

## 6. Scale up with FAISS

NumPy is fine for a few thousand rows but quickly falls over. FAISS is purpose-built for vector search.

We build an `IndexFlatIP` (inner product) on **L2-normalized** vectors — that's mathematically equivalent to exact cosine similarity but with FAISS's optimized SIMD search.

In [ ]:
# Build a FAISS index over normalized review embeddings for fast search.

import faiss

review_embeddings = review_embeddings.astype('float32') #A



# Normalize the review embeddings
review_embeddings_normalized = review_embeddings / np.linalg.norm(review_embeddings, axis=1, keepdims=True)

# Initialize the FAISS index with cosine similarity
index = faiss.IndexFlatIP(review_embeddings_normalized.shape[1])

# Add the normalized review embeddings to the index
index.add(review_embeddings_normalized)

In [ ]:
# Normalize the query embedding
query_embedding_normalized = query_embedding / np.linalg.norm(query_embedding)

# Perform similarity search
k = 5  # Number of similar reviews to retrieve



start_time = time.time()


distances, indices = index.search(query_embedding_normalized, k)

faiss_search_time = time.time() - start_time
print(f"Faiss search time: {faiss_search_time:.4f} seconds")

Faiss search time: 0.0007 seconds

In [ ]:
print(f"Query: {query}")
print("Top hotel with similar reviews using FAISS:")
for i, (idx, distance) in enumerate(zip(indices[0], distances[0]), 1):
    print(f"{i}. {df_paris.iloc[idx]['hotel_name']}")
    print(f"Review: {df_paris.iloc[idx]['review_text']}")
    print(f"Distance: {distance:.4f}")
    print()

Query: Hotel with a view of the Eiffel tower.
Top hotel with similar reviews using FAISS:
1. Pullman Paris Eiffel Tower Hotel
Review: Excellent service. Stunning view of the Eiffel towere from our balcony, The room is gorgeous, comfortable and spacious. Definitely will be recommending this hotel to family and friends. If you’re looking for a hotel that has everything you need in Paris, luxury and view, this is the one.
Distance: 0.8227

2. Pullman Paris Eiffel Tower Hotel
Review: If you stay at this hotel it is for the amazing views of the Eiffel Tower and for the pictures.  The photos and memories of being on the balcony looking at the Eiffel Tower in all its splendor cannot be denied.   When we arrived we were impressed with proximity of hotel to the Eiffel Tower. Definitely within walking distance, 7 minutes, we could even see our hotel when we climbed up the tower later that day . The view itself is spectacular!! We were upgraded to a suite top floor (9th floor) with a balcony. My kids had a seperate room , the view with no balcony, twin beds. They loved the view. That was an experience of a lifetime.   Breakfast was good. I did feel it was overpriced for what you get, cereal, fruit, eggs, different teas, water. But the selection was enormous and
Distance: 0.8078

3. Citadines Tour Eiffel Paris
Review: Had a Eiffel tower balcony view room and the view did not disappoint was absolutely amazing and so nice to see everyone from the room or balcony. Staff at reception were nice and was no problem in checking out 1 hour later for free. Very clean hotel.
Distance: 0.7935

4. Hotel Marignan Champs-Elysees
Review: Very good hotel near the Champs-Elysees.  The superior rooms are very nice and a good size.  The Eiffel Tower suite has an excellent view of the Eiffel Tower. Within walking distance of many things but far enough away from the Champs to feel like you are not right in the middle of a tourist spot.  The thing that makes this hotel is the staff.  They are helpful and willing to do anything they can to make your stay perfect.
Distance: 0.7929

5. Hotel Tourisme Avenue
Review: Nice Hotel only a few minutes away from Eiffel tower. 3 Metro lines in Front of the hotel, supermarket and restaurants very close. Small but nice and clean rooms, good bed, very friendly and helpful personal, very good breakfast buffet.
Distance: 0.7914

In [ ]:
k = 25  # Number of similar reviews to retrieve

start_time = time.time()

distances, indices = index.search(query_embedding_normalized, k)

faiss_search_time = time.time() - start_time
print(f"Faiss search time: {faiss_search_time:.4f} seconds")

print(f"Query: {query}")
print("Top hotel with similar reviews using FAISS:")
for i, (idx, distance) in enumerate(zip(indices[0], distances[0]), 1):
    print(f"{i}. {df_paris.iloc[idx]['hotel_name']}")
    print(f"Review: {df_paris.iloc[idx]['review_text']}")
    print(f"Distance: {distance:.4f}")
    print()

Faiss search time: 0.0006 seconds
Query: Hotel with a view of the Eiffel tower.
Top hotel with similar reviews using FAISS:
1. Pullman Paris Eiffel Tower Hotel
Review: Excellent service. Stunning view of the Eiffel towere from our balcony, The room is gorgeous, comfortable and spacious. Definitely will be recommending this hotel to family and friends. If you’re looking for a hotel that has everything you need in Paris, luxury and view, this is the one.
Distance: 0.8227

2. Pullman Paris Eiffel Tower Hotel
Review: If you stay at this hotel it is for the amazing views of the Eiffel Tower and for the pictures.  The photos and memories of being on the balcony looking at the Eiffel Tower in all its splendor cannot be denied.   When we arrived we were impressed with proximity of hotel to the Eiffel Tower. Definitely within walking distance, 7 minutes, we could even see our hotel when we climbed up the tower later that day . The view itself is spectacular!! We were upgraded to a suite top floor (9th floor) with a balcony. My kids had a seperate room , the view with no balcony, twin beds. They loved the view. That was an experience of a lifetime.   Breakfast was good. I did feel it was overpriced for what you get, cereal, fruit, eggs, different teas, water. But the selection was enormous and
Distance: 0.8078

3. Citadines Tour Eiffel Paris
Review: Had a Eiffel tower balcony view room and the view did not disappoint was absolutely amazing and so nice to see everyone from the room or balcony. Staff at reception were nice and was no problem in checking out 1 hour later for free. Very clean hotel.
Distance: 0.7935

4. Hotel Marignan Champs-Elysees
Review: Very good hotel near the Champs-Elysees.  The superior rooms are very nice and a good size.  The Eiffel Tower suite has an excellent view of the Eiffel Tower. Within walking distance of many things but far enough away from the Champs to feel like you are not right in the middle of a tourist spot.  The thing that makes this hotel is the staff.  They are helpful and willing to do anything they can to make your stay perfect.
Distance: 0.7929

5. Hotel Tourisme Avenue
Review: Nice Hotel only a few minutes away from Eiffel tower. 3 Metro lines in Front of the hotel, supermarket and restaurants very close. Small but nice and clean rooms, good bed, very friendly and helpful personal, very good breakfast buffet.
Distance: 0.7914

6. Passy Eiffel Hotel
Review: Had a great stay at this hotel for a few nights. Comfortable, clean room with a balcony overlooking the street. Not touristy even though it is really close to the Eiffel Tower. Walk the back streets and you find a variety of great places to eat. Hotel staff was helpful and friendly. Would definitely stay there again.
Distance: 0.7904

7. Citadines Tour Eiffel Paris
Review: This property is an Affordable hotel apartment in Paris city center close to Eiffel Tower. We got the room with Eiffel Tower view, our view was the top half of the tower. It was a bit expensive but we were in Paris and wanted this view, also it was one of the reasonable priced for an Eiffel Tower view. We have stayed with Citadines before in Brussels so we know what to expect. Rooms are not luxurious but was cozy, comfortable and spacious enough for our family of 4 with 2 boys. We have a living room area and kitchen with complete supplies you need if you want to cook and eat at the hotel to save a little. The hotel is a few steps away from La Motte Picquet Metro station, there is also a McDonald’s on the same building and a supermarket across the street. There’s free coffee and
Distance: 0.7882

8. Hotel Tourisme Avenue
Review: Hotel was in a great location, many places to eat in close proximity to hotel and walking distances to the Eiffel Tower. Room set up was great for family of 3. The hotel was clean and staff was friendly.
Distance: 0.7852

9. Passy Eiffel Hotel
Review: The hotel is near Eiffel tower and we could see the tower from our hotel balcony. The staff are very friendly and helpful and the breakfast is outstanding. We would like to stay here again when we come back to Paris.
Distance: 0.7832

10. Hotel Marignan Champs-Elysees
Review: Brilliant staff and service, room was cozy and clean! A very romantic evening view of The Eiffel tower too! The location is fantastic, just by the Champs Elysees, perfect for a stroll. Breakfast and dinner at the hotel was very enjoyable.
Distance: 0.7818

11. Hotel La Comtesse
Review: Quaint hotel with great location right by Eiffel Tower. Lots of action nearby and easy access to metro station to go to other areas of Paris. Staff was friendly and helpful.   Highly recommend if you’re staying in Paris
Distance: 0.7754

12. Citadines Tour Eiffel Paris
Review: Citadines for is located in a great place, close to the Eiffel Tower, Paris Military School, shops, restaurant, and accessible public transportation. The lobby was small but cozy, the decor was pretty modern, it was pretty clean, and the more importantly the front desk agents were really helpful and kind, one of them was fluent in 3 languages. The rooms were really a one bedroom apartment, with a full sizr kitchen, and living room. The living had a pullout bed, which was comfortable, with a closet full of sheets and pillows. The view of our apartment was great, from the kitchen we can see the top of the Eiffel Tower, and the neighborhood below.  There is a small courtyard in the rear of the hotel, in case you want to enjoy a cup of coffee outside. For the hotel really thrives
Distance: 0.7753

13. Pullman Paris Eiffel Tower Hotel
Review: This is a great hotel with a perfect location for sightseeing. Stayed her for three nights in a Eiffel view balcony room, view was amazing, and the amenities and comfort of the room were outstanding.  Staff were very friendly and accommodating, Dinner and breakfast in the restaurant were excellent, high quality and well priced for the area. Hotel is central to most attractions, and there is a metro station at the end of the street.  Highly recommend and will return when in Paris next.
Distance: 0.7750

14. Pullman Paris Eiffel Tower Hotel
Review: This hotel is wonderful.  The location is next to the Eiffel Tower, plenty of restaurants and shops in the area.  The breakfast buffet (complementary) is fantastic, rooms were comfortable as was the bed. I highly recommend this hotel.
Distance: 0.7740

15. Cler Hotel
Review: Very nice hotel! Staff is great, very accommodating. Would come back again. It is pretty small- the rooms are smaller than they look online. Eiffel tower room has a great view but the other rooms have nice views of the streets.
Distance: 0.7736

16. Hotel Tourisme Avenue
Review: The hotel is east to find with its white exterior and large letters identifying it on a busy street near the Eiffel Tower.   Lots of nice cafes next door and the metro stop is steps from the lobby. The reception area is modern, clean and spacious with a friendly, professional and very helpful staff. Everything is up to date in the public areas, and the hotel has room for 4 with luggage.   The room is clean, comfortable, well lit, and the beds are excellent.   The bathroom has a great shower with more room than usual for Europe.  We would stay here the next time we are in Paris.
Distance: 0.7671

17. Pullman Paris Eiffel Tower Hotel
Review: Ok hotel partial view of Eiffel Tower because your a block away. Expensive , not a huge room. Staff was ok , bell staff probably more then front desk staff. Breakfast was the highlight, came with the room fee. I guess I felt you can do better as to choices to stay. Close to the Tower and the Rodin   museum . Paris is all about your wallet so be prepared to play
Distance: 0.7668

18. citizenM Paris Champs-Elysees
Review:  Amazing weekend with so much to see . The hotel was the perfect location to visit all sites by walking or taking the metro that is right near the hotel .  The courtyard and the view of the Eiffel Tower was amazing.
Distance: 0.7636

19. Passy Eiffel Hotel
Review: Great location, I found the hotel very classic and fit in as well with the surrounding neighborhood, my room was comfortable, clean and well supplied. The location was excellent, a 15 minute walk to the Eiffel Tower and cruise boat location, we were able to walk thru the charming neighborhoods to the Arc de Triomphe, Catacombs of Paris, Louvre Museum and Notre Dame. There were many restaurant's minutes from the Hotel.
Distance: 0.7632

20. Cler Hotel
Review: Wonderful hotel. Very close to the Eiffel Tower. Lots of restaurants and shops. Very clean. Helpful, kind staff. The concierge saw I was very tired and allowed me to get my room early. They stored our bags after checkout so we could explore more before we had to leave. Just an overall lovely hotel.
Distance: 0.7626

21. Passy Eiffel Hotel
Review: The location is outstanding. The rooms with the balconies have the most stunning view of Eiffel Tower. The staff are just wonderful and nothing was too much trouble. Hotel amenities are great. Many restaurants and cafes around hotel but plentiful offering within also. Will most definitely return. Thank you
Distance: 0.7618

22. Hotel La Comtesse
Review: The hotel was everything I expected and more!  Sitting in front  in the little cafe with the view!!! Amazing!! Your staff was very helpful and supportive. The room, loved it! The view of the Eiffel Tower was amazing.
Distance: 0.7614

23. Hotel La Comtesse
Review: My boyfriend and I were staying outside of Paris for his business trip in August 2022 and booked a last minute overnight stay in the city. The staff was friendly and upgraded our room to a center view of the Eiffel Tower when our original view was from the side. I booked this hotel for the view so I was very excited to get a better view. I felt very safe here since all the doors and elevator required a room key to work. The room was a great size for Paris and the bathroom was large as well. It has modern upgrades while still having the Parisian charm. The A/C worked great and the bed was comfortable. The location of this hotel is also amazing and the metro isn’t needed to get to a lot of great places. We would definitely book here again!
Distance: 0.7588

24. Passy Eiffel Hotel
Review: Easy booking. Very nice small hotel, well situated near the Eiffel Tower, clean rooms, good bathroom facilities and breakfast available. Polite and nice staff. I have stayed here several times and recommend.
Distance: 0.7545

25. Hotel La Comtesse
Review: Great hotel and caring staff, and they are always ready to provide anything needed. Great location for visiting the Eiffel Tower, Louvre museum, royal palaces, and great restaurants.  Rooms are Very well appointed, with very comfortable beds/bedding. Good selection of breakfast items, from hot to cold. Great place to stay!
Distance: 0.7541

In [ ]:
# Aggregate many retrieved reviews into hotel-level recommendations.

k = 120  # Number of similar reviews to retrieve

start_time = time.time()

distances, indices = index.search(query_embedding_normalized, k)

faiss_search_time = time.time() - start_time
print(f"Faiss search time: {faiss_search_time:.4f} seconds")

hotel_info = {}

for idx, distance in zip(indices[0], distances[0]):
    hotel_name = df_paris.iloc[idx]['hotel_name']
    if hotel_name not in hotel_info:
        hotel_info[hotel_name] = {
            'description': df_paris.iloc[idx]['hotel_description'],
            'reviews': [],
            'distances': []
        }
    hotel_info[hotel_name]['reviews'].append(df_paris.iloc[idx]['review_text'])
    hotel_info[hotel_name]['distances'].append(distance)

for hotel_name in hotel_info:
    hotel_info[hotel_name]['overall_distance'] = np.mean(hotel_info[hotel_name]['distances'])
    hotel_info[hotel_name]['num_reviews'] = len(hotel_info[hotel_name]['reviews'])

filtered_hotels = {hotel_name: hotel_data for hotel_name, hotel_data in hotel_info.items() if hotel_data['num_reviews'] >= 2}

sorted_hotels = sorted(filtered_hotels.items(), key=lambda x: x[1]['overall_distance'], reverse=True)

print(f"Query: {query}")
print("Top hotels with similar reviews using FAISS:")
for i, (hotel_name, hotel_data) in enumerate(sorted_hotels, 1):
    print(f"{i}. {hotel_name}")
    print(f"Description: {hotel_data['description']}")
    print(f"Overall Distance: {hotel_data['overall_distance']:.4f}")
    print(f"Number of Reviews: {hotel_data['num_reviews']}")
    print("Reviews:")
    for review in hotel_data['reviews']:
        print(f"- {review}")
    print()

Faiss search time: 0.0007 seconds
Query: Hotel with a view of the Eiffel tower.
Top hotels with similar reviews using FAISS:
1. Citadines Tour Eiffel Paris
Description: None
Overall Distance: 0.7461
Number of Reviews: 10
Reviews:
- Had a Eiffel tower balcony view room and the view did not disappoint was absolutely amazing and so nice to see everyone from the room or balcony. Staff at reception were nice and was no problem in checking out 1 hour later for free. Very clean hotel.
- This property is an Affordable hotel apartment in Paris city center close to Eiffel Tower. We got the room with Eiffel Tower view, our view was the top half of the tower. It was a bit expensive but we were in Paris and wanted this view, also it was one of the reasonable priced for an Eiffel Tower view. We have stayed with Citadines before in Brussels so we know what to expect. Rooms are not luxurious but was cozy, comfortable and spacious enough for our family of 4 with 2 boys. We have a living room area and kitchen with complete supplies you need if you want to cook and eat at the hotel to save a little. The hotel is a few steps away from La Motte Picquet Metro station, there is also a McDonald’s on the same building and a supermarket across the street. There’s free coffee and
- Citadines for is located in a great place, close to the Eiffel Tower, Paris Military School, shops, restaurant, and accessible public transportation. The lobby was small but cozy, the decor was pretty modern, it was pretty clean, and the more importantly the front desk agents were really helpful and kind, one of them was fluent in 3 languages. The rooms were really a one bedroom apartment, with a full sizr kitchen, and living room. The living had a pullout bed, which was comfortable, with a closet full of sheets and pillows. The view of our apartment was great, from the kitchen we can see the top of the Eiffel Tower, and the neighborhood below.  There is a small courtyard in the rear of the hotel, in case you want to enjoy a cup of coffee outside. For the hotel really thrives
- We arrived at the Hotel at 10am, check in was supposed to start from 3pm. 'Nes' (I hope I got her name right) saw us from the counter and offered us early check in, free of charge.   My friends and I booked 2 rooms from this Aparthotel for 3 nights. Both rooms were clean and spacious, with great view of the Eiffel Tower too (around half). Do take note that you have to select the right room type when booking tho, some room types do not face the Eiffel Tower. The room has cooking utensils, water heater works great, even the tap has hot water (and I really mean hot water). The only tiny drawback about this hotel is the lack of slippers.    Thermostat works well for my room, with options to cooling and heating the room. The rooms can get pretty dry during the night. Some rooms came
- This is a great place to stay. The staff are all really kind and helpful. The rooms are so nice and very clean. I loved being able to use the kitchenette. The views are amazing. You can see the Eiffel Tower from some rooms, but the view over the back garden is also really pretty, especially the sky over the roofs of the neighboring buildings. The location is super convenient. There is a metro station right across the street, the Eiffel Tower is a 15 minute walk away, and there is a market across the street twice a week with fantastic produce. Plus, there are a ton of great cafes and bakeries on both streets next to the hotel. The basement has a washing machine and clothes dryer, plus the bathroom has a towel warmer and clothesline, which makes doing laundry very easy.
- In general, this hotel gets the job done. It's not the best for staycations but it's good enough if you're just spending most of the day touring. The rooms were spacious and had a nice peek at the Eiffel Tower. I encountered some hiccups though like a broken bathtub drain and bath towels not being replaced. Our room was facing the train station but we didn't find the noise bothersome at all as the others who have reviewed about it.   The location was very convenient. It's right beside a train station that connects you to the rest of Paris, and there are a lot of restaurants and stores nearby.
- This hotel was in a perfect area. Thw rooms are small, so dont expect American style rooms. But we only slept there and showered. So it was perfect. Coffee is provided in the lobby. They offer breakfast for a small cost. We didn't try it. My husband got the room with the view of the Effiel Tower. Couldn't have been a better choice. The hotel was about a 5 min scooter ride to the tower as well. McDonald's is not the same in france, so I wouldn't recommend going to the one by the hotel. The bakery was excellent as well as the other restaurants around. I can't wait to go back!
- I thoroughly enjoyed my one-month stay in this establishment between late June to mid-July. The hotel is conveniently situated near a metro station and within viewing/walking distance of the Eiffel Tower. As for the room, the kitchenette was fully equipped with additional appliances (a tea kettle and espresso machine), and the sleeping accommodations were comfortable and cool (with AC). The hotel staff were always professional, friendly, and courteous. Also, great outdoor patio and garden to lounge!
- This place has become our home in Paris. We know the area very well as we lived around for some time, and staying here allows us to reconnect with our old area. The front desk staff is amazing, and the property is very well kept. We had another Eiffel Tower view studio, and waking up to that spectacular view was amazing. The studio was very spacious and had all the basics. The hotel is well connected by Metro and Bus and you can get anywhere very quick. Overall a recommended place to stay.
- This hotel was recommended by our Travel Advisor for our first trip to Paris and did not disappoint.  The location is  wonderful and it is a very easy walk up to the Eiffel Tower.  The front desk staff was very helpful and kind with suggestions and directions especially Valentina!    The rooms are a great size and having the apartment style set up is wonderful.  We had an amazing view from our rooms and could not have asked for more to make our little home away from home feel great while we were there!

2. Pullman Paris Eiffel Tower Hotel
Description: Stay at the Pullman Paris Tour Eiffel, the favorite hotel for travelers to Paris. At the foot of the Eiffel Tower, the hotel is the ideal starting point for visiting the capital and its main monuments. Offering great comfort and excellent value for money, it offers a wide range of services: 24-hour reception, concierge, room service, ... Its spacious and bright rooms have a flat-screen TV, WiFi connection, minibar and docking station for Alexa by Amazon. Some offer a breathtaking view of the Eiffel Tower. Visit FRAME, its Californian brasserie for brunch or dinner and savor the fresh produces from the garden. Also take advantage of the hotel's fitness room and its hi-tech equipment. Don't wait any longer to book your stay at the Pullman Paris Tour Eiffel and immerse yourself in one of Paris’s most prestigious districts.
Overall Distance: 0.7413
Number of Reviews: 16
Reviews:
- Excellent service. Stunning view of the Eiffel towere from our balcony, The room is gorgeous, comfortable and spacious. Definitely will be recommending this hotel to family and friends. If you’re looking for a hotel that has everything you need in Paris, luxury and view, this is the one.
- If you stay at this hotel it is for the amazing views of the Eiffel Tower and for the pictures.  The photos and memories of being on the balcony looking at the Eiffel Tower in all its splendor cannot be denied.   When we arrived we were impressed with proximity of hotel to the Eiffel Tower. Definitely within walking distance, 7 minutes, we could even see our hotel when we climbed up the tower later that day . The view itself is spectacular!! We were upgraded to a suite top floor (9th floor) with a balcony. My kids had a seperate room , the view with no balcony, twin beds. They loved the view. That was an experience of a lifetime.   Breakfast was good. I did feel it was overpriced for what you get, cereal, fruit, eggs, different teas, water. But the selection was enormous and
- This is a great hotel with a perfect location for sightseeing. Stayed her for three nights in a Eiffel view balcony room, view was amazing, and the amenities and comfort of the room were outstanding.  Staff were very friendly and accommodating, Dinner and breakfast in the restaurant were excellent, high quality and well priced for the area. Hotel is central to most attractions, and there is a metro station at the end of the street.  Highly recommend and will return when in Paris next.
- This hotel is wonderful.  The location is next to the Eiffel Tower, plenty of restaurants and shops in the area.  The breakfast buffet (complementary) is fantastic, rooms were comfortable as was the bed. I highly recommend this hotel.
- Ok hotel partial view of Eiffel Tower because your a block away. Expensive , not a huge room. Staff was ok , bell staff probably more then front desk staff. Breakfast was the highlight, came with the room fee. I guess I felt you can do better as to choices to stay. Close to the Tower and the Rodin   museum . Paris is all about your wallet so be prepared to play
- Just back from a stay at this hotel, firstly I wasn’t sure what to expect due to some very mixed reviews of the hotel.  I needn’t have worried it was a fantastic stay.   I’m afraid I didn’t get any names but the young lady that helped 2 newly single ladies check into their instagramable room to the lovely gentleman in the evening that sorted us out an extra quilt and made my evening by complimenting my perfume and said I smelt like vanilla caramel.   The bathroom was lovely clean and modern, the room and bed comfy and clean.  But the best part was the amazing view from the balcony. Sitting outside even on 23rd November was so special - yes it really is that good to see the Eiffel Tower that close.   the only negative was the slightly confusing room rate and bill.  But overall a
- The location was fantastic!  We had a balcony and an awesome view of the Eiffel Tower.  It was an easy walk to the ET as well as to the hop on / off bus.  Also really close to Le Pont de Dir-Hakeim Bridge where we had to meet for a dinner cruise along the Seine.  The hotel was also the meeting point for a number of tours including the Claude Monet Gardens tour and the Versailles Palace.  The Australian Embassy was also in the same street.  Across the road was a stadium where there were numerous events during our stay.  The hotel itself was really nice and service was exceptional.  The Hotel Restaurant was first class with regards to service food and ambience.  Breakfast was a treat as well.  The room was a good size given it was in the city.  The balcony made it that much
- Hotel fabulous location close to the    Eiffel Tower and the toot toot bus stop great for touring Paris. Breakfast at the Pullman was a good selection room was clean and good standard. Staff very helpful and professional. Would recommend this hotel only thing is maybe upgrade the windows for soundproofing a bit more if a light sleeper as street noise can be heard other than that great stay
- The reason why people book this hotel, and there's one reason only--is the proximity to the Eiffel Tower. Do not book here for luxury or even cleanliness. However, I knew I wasn't booking  5 or even 4 star hotel. It is amazing to be able to come out front and take pix with the Eiffel Tower. In addition, there are 3 restaurants that seem to be open until early in the morning--so again, location, location, location! (However be careful bc they do have lots of hidden fees, for mediocre food when you receive your check.) But anyway back to the Pullman, my room was a garden view and the balcony was nice. However, the carpets are filthy an should have been deep cleaned before anyone was assigned this room. Also, there are literal holes in the wall where the toilet dispenser goes. The
- This is a very good hotel. The location is central and lots of the sights are within easy distance. The events/reservations team were very helpful before our stay and during. This hotel has one of the best breakfasts I have ever seen. The rooms are some of the largest and modern in Paris. If you are looking for a standard western hotel opposed Parisian boutique, I’d highly recommend. The only downsides are that the reception is very slow and the rooms are in need of a little TLC. We stayed in the Trocadero suite and I was a little disappointed in the suite, as there were lots of little things that were broken or well worn. The Eiffel Tower views are 10/10.
- We stayed two nights at the Hotel. Checking in was easy, in fact we got there at 10:30 a.m. expecting our room was not ready, but we  we were  able to go to our room.  The room was large enough, and had a nice patio with a great view from the 9th floor. The elevators were working well, and we had very little waiting time. The staff in all areas were very friendly and willing to help.  Our breakfast was included in the price, and it was very well set up, and delicious. The location was amazingly central to so many things, many choices of restaurants very close to the hotel. We went to the bar on the top floor, but though you could see the Eiffel Tower all lit up, it was not an inviting atmosphere. They wanted you buying drinks and not just coming for a picture. They only really
- We booked through Expedia & paid for a room with a balcony & Eiffel Tower view, it was 100% worth it. We were able to sit out with coffees & watch the tower glitter at night. We arrived ed before check in time & we were offered a room on the second floor that was ready but they advised if we wanted a better view to come back at 3pm check in time & we could get this. We did, and had a room on the fourth floor and I couldn’t fault it. The room is clean and very modern, we were there during the Rugby World Cup 23 & were given some rugby themed gifts by staff. The bathroom is very spacious. I was very pleased with this room, if it seems out of your price range you could book this place for just one night to enjoy the views (this is what we did!)
- The room view is sooooo good, recommend to request high floor to not hearing a noise disturb from the road and any smell of cigaratte from ground floor ( im on second floor so i experienced both of them) but i dont mind. Eiffel view is perfect for me!
- Excellent staff, great position within 2 mins to the Eiffel Tower. Breakfast very good too. If you want something near to the Eiffel Tower this is as good as it gets for a fair price. The staff were outstanding, all very happy to serve us. Would def come back here with my wife if we were to come back to Paris.
- Our second stayed in Patis at Pullman Eiffel Tower the hotel has such a great location and great view but quite expensive and the breakfast was overcrowded with people could not move.   Overall, just great location, location, location and a great view.
- All I can say is location, location, location .   We had a Eiffel Tower view room and we’re upgraded to a suite (104) all I can say is spend the money on a balcony with the tower view. It’s worth every cent!   I would say this is where I want to stay again, why? Sitting 3-4 times a day admiring the tower on my balcony as we have breakfast, watching the light show….spectacular view.   Our tour to palace of Versailles was from the hotel as the meeting point. When we did the hop on hop off bus stop 8 & 9 is here and lastly we could walk to our river cruise. Very convenient .   Restaurants all in meters from the hotel and a supermarket   We didn’t eat here or got to the bay on level 10.   Staff were helpful in every aspect. I could not fault anything as we are sad to leave

3. Passy Eiffel Hotel
Description: Looking for a place to stay in Paris? Then look no further than Passy Eiffel Hotel, a romantic hotel that brings the best of Paris to your doorstep. Free wifi is offered to guests, and rooms at Passy Eiffel Hotel offer flat screen TV, air conditioning, and a minibar.During your stay, take advantage of some of the amenities offered, including a 24 hour front desk , honnesty bar and baggage storage. Guests of Passy Eiffel Hotel are also welcome to enjoy breakfast buffet, located on site. For travelers arriving by car, parking is available across the street.Given the close proximity of popular landmarks, such as Eiffel tower and Champs Elysees. Guests of Passy Eiffel Hotel can easily experience some of Paris' most well known attractions. We’re sure you’ll enjoy your stay at Passy Eiffel Hotel as you experience everything Paris has to offer.
Overall Distance: 0.7394
Number of Reviews: 18
Reviews:
- Had a great stay at this hotel for a few nights. Comfortable, clean room with a balcony overlooking the street. Not touristy even though it is really close to the Eiffel Tower. Walk the back streets and you find a variety of great places to eat. Hotel staff was helpful and friendly. Would definitely stay there again.
- The hotel is near Eiffel tower and we could see the tower from our hotel balcony. The staff are very friendly and helpful and the breakfast is outstanding. We would like to stay here again when we come back to Paris.
- Great location, I found the hotel very classic and fit in as well with the surrounding neighborhood, my room was comfortable, clean and well supplied. The location was excellent, a 15 minute walk to the Eiffel Tower and cruise boat location, we were able to walk thru the charming neighborhoods to the Arc de Triomphe, Catacombs of Paris, Louvre Museum and Notre Dame. There were many restaurant's minutes from the Hotel.
- The location is outstanding. The rooms with the balconies have the most stunning view of Eiffel Tower. The staff are just wonderful and nothing was too much trouble. Hotel amenities are great. Many restaurants and cafes around hotel but plentiful offering within also. Will most definitely return. Thank you
- Easy booking. Very nice small hotel, well situated near the Eiffel Tower, clean rooms, good bathroom facilities and breakfast available. Polite and nice staff. I have stayed here several times and recommend.
- Perfect location to walk to Eiffel Tower 20 mins, use the Batobus to sail to all usual tourist destinations to avoid the heavy Paris traffic, convenient bakery next door for grab and go breakfast and delicious treats, walkable area and mins from seeing Eiffel Tower and the Seine River, had a room with a partial view of E Tower,friendly and helpful front desk staff, had difficulty returning from Roland Garros as no direct public transport to hotel area. Would definitely stay here again.
- Gorgeous hotel in the lovely and quiet area of Passy. 10 mins walk to the Eiffel Tower with views of the tower from the rooms. Great breakfast. Charming courtyard behind reception. Super and friendly staff who were all lovely throughout our stay. We’ll be back
- Nice and comfortable boutique hotel within walking distance to Eiffel Tower , Trocadero and restaurants. I requested a room with a view to the tower and it was lovely. Walking distance to shopping too. Very nice and friendly staff. Rooms are small similar to many many hotels in Europe.  Affordable rates too. Very nice and attentive staff ! I would stay here again.
- A lovely hotel in a central location. Passy is a great neighbourhood with everything you need in easy walking distance. Hotel is charming and well maintained. We had a view of the Eiffel Tower which was an added bonus.

### Aggregate by hotel

A single hotel may show up many times in the top-k. Group by hotel and rank by mean cosine to surface *places* rather than individual reviews.

In [ ]:
# Wrap the FAISS setup into reusable helper functions.

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

def get_embeddings(data, model):
    """
    Generates embeddings for a list of text data.

    Args:
        data (list): A list of strings.
        model (SentenceTransformer): The pre-trained sentence transformer model.

    Returns:
        np.ndarray: The embeddings of the input data.
    """
    embeddings = model.encode(data, show_progress_bar=False).astype('float32')
    return embeddings

def search_faiss_index(query_embedding, faiss_index, k=5):
    """
    Performs a semantic search on a FAISS index using a query embedding.

    Args:
        query_embedding (np.ndarray): The embedding of the query string.
        faiss_index (faiss.IndexFlatIP): The FAISS index object.
        k (int): The number of nearest neighbors to retrieve.

    Returns:
        tuple: A tuple containing:
            - distances (np.ndarray): The distances of the retrieved neighbors.
            - indices (np.ndarray): The indices of the retrieved neighbors in the original data.
    """
    # Normalize the query embedding
    query_embedding_normalized = query_embedding / np.linalg.norm(query_embedding)
    distances, indices = faiss_index.search(query_embedding_normalized, k)
    return distances, indices

def create_faiss_index(embeddings):
    """
    Creates a FAISS index from a set of embeddings.

    Args:
        embeddings (np.ndarray): The embeddings to index.

    Returns:
        faiss.IndexFlatIP: The created FAISS index object.
    """
    # Normalize the embeddings
    embeddings_normalized = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)
    # Initialize the FAISS index with cosine similarity (Inner Product)
    index = faiss.IndexFlatIP(embeddings_normalized.shape[1])
    # Add the normalized embeddings to the index
    index.add(embeddings_normalized)
    return index

# Example usage (assuming 'reviews' and 'model' are defined from previous code):
reviews = df_paris['review_text'].tolist()
model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)
if torch.cuda.is_available():
    model = model.to('cuda')

review_embeddings = get_embeddings(reviews, model)
faiss_index = create_faiss_index(review_embeddings)

WARNING:transformers_modules.nomic-ai.nomic-bert-2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

Query: Hotel with a view of the Eiffel tower.
Top hotel with similar reviews using FAISS:
1. Pullman Paris Eiffel Tower Hotel
Review: Excellent service. Stunning view of the Eiffel towere from our balcony, The room is gorgeous, comfortable and spacious. Definitely will be recommending this hotel to family and friends. If you’re looking for a hotel that has everything you need in Paris, luxury and view, this is the one.
Cosine Similarity: 0.8227

2. Pullman Paris Eiffel Tower Hotel
Review: If you stay at this hotel it is for the amazing views of the Eiffel Tower and for the pictures.  The photos and memories of being on the balcony looking at the Eiffel Tower in all its splendor cannot be denied.   When we arrived we were impressed with proximity of hotel to the Eiffel Tower. Definitely within walking distance, 7 minutes, we could even see our hotel when we climbed up the tower later that day . The view itself is spectacular!! We were upgraded to a suite top floor (9th floor) with a balcony. My kids had a seperate room , the view with no balcony, twin beds. They loved the view. That was an experience of a lifetime.   Breakfast was good. I did feel it was overpriced for what you get, cereal, fruit, eggs, different teas, water. But the selection was enormous and
Cosine Similarity: 0.8078

3. Citadines Tour Eiffel Paris
Review: Had a Eiffel tower balcony view room and the view did not disappoint was absolutely amazing and so nice to see everyone from the room or balcony. Staff at reception were nice and was no problem in checking out 1 hour later for free. Very clean hotel.
Cosine Similarity: 0.7935

4. Hotel Marignan Champs-Elysees
Review: Very good hotel near the Champs-Elysees.  The superior rooms are very nice and a good size.  The Eiffel Tower suite has an excellent view of the Eiffel Tower. Within walking distance of many things but far enough away from the Champs to feel like you are not right in the middle of a tourist spot.  The thing that makes this hotel is the staff.  They are helpful and willing to do anything they can to make your stay perfect.
Cosine Similarity: 0.7929

5. Hotel Tourisme Avenue
Review: Nice Hotel only a few minutes away from Eiffel tower. 3 Metro lines in Front of the hotel, supermarket and restaurants very close. Small but nice and clean rooms, good bed, very friendly and helpful personal, very good breakfast buffet.
Cosine Similarity: 0.7914

## 7. Comparing FAISS index types

- **Flat** — exact, full-scan; slow on big corpora.
- **HNSW** — graph-based, fast & accurate, more memory.
- **IVF-PQ** — clustered + quantized, very fast, lossy.

For a small corpus the latency differences are tiny; on millions of vectors they're decisive.

In [ ]:
query = "Hotel with a view of the Eiffel tower."
query_embedding = get_embeddings([query], model)

k = 25
distances, indices = search_faiss_index(query_embedding, faiss_index, k=k)

print(f"Query: {query}")
print("Top hotel with similar reviews using FAISS:")
for i, (idx, distance) in enumerate(zip(indices[0], distances[0]), 1):
    print(f"{i}. {df_paris.iloc[idx]['hotel_name']}")
    print(f"Review: {df_paris.iloc[idx]['review_text']}")
    # Note: With normalized embeddings and IndexFlatIP, the distance is the inner product,
    # which is equal to the cosine similarity.
    print(f"Cosine Similarity: {distance:.4f}")
    print()

Query: Hotel with a view of the Eiffel tower.
Top hotel with similar reviews using FAISS:
1. Pullman Paris Eiffel Tower Hotel
Review: Excellent service. Stunning view of the Eiffel towere from our balcony, The room is gorgeous, comfortable and spacious. Definitely will be recommending this hotel to family and friends. If you’re looking for a hotel that has everything you need in Paris, luxury and view, this is the one.
Cosine Similarity: 0.8227

2. Pullman Paris Eiffel Tower Hotel
Review: If you stay at this hotel it is for the amazing views of the Eiffel Tower and for the pictures.  The photos and memories of being on the balcony looking at the Eiffel Tower in all its splendor cannot be denied.   When we arrived we were impressed with proximity of hotel to the Eiffel Tower. Definitely within walking distance, 7 minutes, we could even see our hotel when we climbed up the tower later that day . The view itself is spectacular!! We were upgraded to a suite top floor (9th floor) with a balcony. My kids had a seperate room , the view with no balcony, twin beds. They loved the view. That was an experience of a lifetime.   Breakfast was good. I did feel it was overpriced for what you get, cereal, fruit, eggs, different teas, water. But the selection was enormous and
Cosine Similarity: 0.8078

3. Citadines Tour Eiffel Paris
Review: Had a Eiffel tower balcony view room and the view did not disappoint was absolutely amazing and so nice to see everyone from the room or balcony. Staff at reception were nice and was no problem in checking out 1 hour later for free. Very clean hotel.
Cosine Similarity: 0.7935

4. Hotel Marignan Champs-Elysees
Review: Very good hotel near the Champs-Elysees.  The superior rooms are very nice and a good size.  The Eiffel Tower suite has an excellent view of the Eiffel Tower. Within walking distance of many things but far enough away from the Champs to feel like you are not right in the middle of a tourist spot.  The thing that makes this hotel is the staff.  They are helpful and willing to do anything they can to make your stay perfect.
Cosine Similarity: 0.7929

5. Hotel Tourisme Avenue
Review: Nice Hotel only a few minutes away from Eiffel tower. 3 Metro lines in Front of the hotel, supermarket and restaurants very close. Small but nice and clean rooms, good bed, very friendly and helpful personal, very good breakfast buffet.
Cosine Similarity: 0.7914

6. Passy Eiffel Hotel
Review: Had a great stay at this hotel for a few nights. Comfortable, clean room with a balcony overlooking the street. Not touristy even though it is really close to the Eiffel Tower. Walk the back streets and you find a variety of great places to eat. Hotel staff was helpful and friendly. Would definitely stay there again.
Cosine Similarity: 0.7904

7. Citadines Tour Eiffel Paris
Review: This property is an Affordable hotel apartment in Paris city center close to Eiffel Tower. We got the room with Eiffel Tower view, our view was the top half of the tower. It was a bit expensive but we were in Paris and wanted this view, also it was one of the reasonable priced for an Eiffel Tower view. We have stayed with Citadines before in Brussels so we know what to expect. Rooms are not luxurious but was cozy, comfortable and spacious enough for our family of 4 with 2 boys. We have a living room area and kitchen with complete supplies you need if you want to cook and eat at the hotel to save a little. The hotel is a few steps away from La Motte Picquet Metro station, there is also a McDonald’s on the same building and a supermarket across the street. There’s free coffee and
Cosine Similarity: 0.7882

8. Hotel Tourisme Avenue
Review: Hotel was in a great location, many places to eat in close proximity to hotel and walking distances to the Eiffel Tower. Room set up was great for family of 3. The hotel was clean and staff was friendly.
Cosine Similarity: 0.7852

9. Passy Eiffel Hotel
Review: The hotel is near Eiffel tower and we could see the tower from our hotel balcony. The staff are very friendly and helpful and the breakfast is outstanding. We would like to stay here again when we come back to Paris.
Cosine Similarity: 0.7832

10. Hotel Marignan Champs-Elysees
Review: Brilliant staff and service, room was cozy and clean! A very romantic evening view of The Eiffel tower too! The location is fantastic, just by the Champs Elysees, perfect for a stroll. Breakfast and dinner at the hotel was very enjoyable.
Cosine Similarity: 0.7818

11. Hotel La Comtesse
Review: Quaint hotel with great location right by Eiffel Tower. Lots of action nearby and easy access to metro station to go to other areas of Paris. Staff was friendly and helpful.   Highly recommend if you’re staying in Paris
Cosine Similarity: 0.7754

12. Citadines Tour Eiffel Paris
Review: Citadines for is located in a great place, close to the Eiffel Tower, Paris Military School, shops, restaurant, and accessible public transportation. The lobby was small but cozy, the decor was pretty modern, it was pretty clean, and the more importantly the front desk agents were really helpful and kind, one of them was fluent in 3 languages. The rooms were really a one bedroom apartment, with a full sizr kitchen, and living room. The living had a pullout bed, which was comfortable, with a closet full of sheets and pillows. The view of our apartment was great, from the kitchen we can see the top of the Eiffel Tower, and the neighborhood below.  There is a small courtyard in the rear of the hotel, in case you want to enjoy a cup of coffee outside. For the hotel really thrives
Cosine Similarity: 0.7753

13. Pullman Paris Eiffel Tower Hotel
Review: This is a great hotel with a perfect location for sightseeing. Stayed her for three nights in a Eiffel view balcony room, view was amazing, and the amenities and comfort of the room were outstanding.  Staff were very friendly and accommodating, Dinner and breakfast in the restaurant were excellent, high quality and well priced for the area. Hotel is central to most attractions, and there is a metro station at the end of the street.  Highly recommend and will return when in Paris next.
Cosine Similarity: 0.7750

14. Pullman Paris Eiffel Tower Hotel
Review: This hotel is wonderful.  The location is next to the Eiffel Tower, plenty of restaurants and shops in the area.  The breakfast buffet (complementary) is fantastic, rooms were comfortable as was the bed. I highly recommend this hotel.
Cosine Similarity: 0.7740

15. Cler Hotel
Review: Very nice hotel! Staff is great, very accommodating. Would come back again. It is pretty small- the rooms are smaller than they look online. Eiffel tower room has a great view but the other rooms have nice views of the streets.
Cosine Similarity: 0.7736

16. Hotel Tourisme Avenue
Review: The hotel is east to find with its white exterior and large letters identifying it on a busy street near the Eiffel Tower.   Lots of nice cafes next door and the metro stop is steps from the lobby. The reception area is modern, clean and spacious with a friendly, professional and very helpful staff. Everything is up to date in the public areas, and the hotel has room for 4 with luggage.   The room is clean, comfortable, well lit, and the beds are excellent.   The bathroom has a great shower with more room than usual for Europe.  We would stay here the next time we are in Paris.
Cosine Similarity: 0.7671

17. Pullman Paris Eiffel Tower Hotel
Review: Ok hotel partial view of Eiffel Tower because your a block away. Expensive , not a huge room. Staff was ok , bell staff probably more then front desk staff. Breakfast was the highlight, came with the room fee. I guess I felt you can do better as to choices to stay. Close to the Tower and the Rodin   museum . Paris is all about your wallet so be prepared to play
Cosine Similarity: 0.7668

18. citizenM Paris Champs-Elysees
Review:  Amazing weekend with so much to see . The hotel was the perfect location to visit all sites by walking or taking the metro that is right near the hotel .  The courtyard and the view of the Eiffel Tower was amazing.
Cosine Similarity: 0.7636

19. Passy Eiffel Hotel
Review: Great location, I found the hotel very classic and fit in as well with the surrounding neighborhood, my room was comfortable, clean and well supplied. The location was excellent, a 15 minute walk to the Eiffel Tower and cruise boat location, we were able to walk thru the charming neighborhoods to the Arc de Triomphe, Catacombs of Paris, Louvre Museum and Notre Dame. There were many restaurant's minutes from the Hotel.
Cosine Similarity: 0.7632

20. Cler Hotel
Review: Wonderful hotel. Very close to the Eiffel Tower. Lots of restaurants and shops. Very clean. Helpful, kind staff. The concierge saw I was very tired and allowed me to get my room early. They stored our bags after checkout so we could explore more before we had to leave. Just an overall lovely hotel.
Cosine Similarity: 0.7626

21. Passy Eiffel Hotel
Review: The location is outstanding. The rooms with the balconies have the most stunning view of Eiffel Tower. The staff are just wonderful and nothing was too much trouble. Hotel amenities are great. Many restaurants and cafes around hotel but plentiful offering within also. Will most definitely return. Thank you
Cosine Similarity: 0.7618

22. Hotel La Comtesse
Review: The hotel was everything I expected and more!  Sitting in front  in the little cafe with the view!!! Amazing!! Your staff was very helpful and supportive. The room, loved it! The view of the Eiffel Tower was amazing.
Cosine Similarity: 0.7614

23. Hotel La Comtesse
Review: My boyfriend and I were staying outside of Paris for his business trip in August 2022 and booked a last minute overnight stay in the city. The staff was friendly and upgraded our room to a center view of the Eiffel Tower when our original view was from the side. I booked this hotel for the view so I was very excited to get a better view. I felt very safe here since all the doors and elevator required a room key to work. The room was a great size for Paris and the bathroom was large as well. It has modern upgrades while still having the Parisian charm. The A/C worked great and the bed was comfortable. The location of this hotel is also amazing and the metro isn’t needed to get to a lot of great places. We would definitely book here again!
Cosine Similarity: 0.7588

24. Passy Eiffel Hotel
Review: Easy booking. Very nice small hotel, well situated near the Eiffel Tower, clean rooms, good bathroom facilities and breakfast available. Polite and nice staff. I have stayed here several times and recommend.
Cosine Similarity: 0.7545

25. Hotel La Comtesse
Review: Great hotel and caring staff, and they are always ready to provide anything needed. Great location for visiting the Eiffel Tower, Louvre museum, royal palaces, and great restaurants.  Rooms are Very well appointed, with very comfortable beds/bedding. Good selection of breakfast items, from hot to cold. Great place to stay!
Cosine Similarity: 0.7541

In [ ]:
# Build and benchmark several FAISS index types.

import time


# Flat index (L2 distance)
index_flat = faiss.IndexFlatL2(review_embeddings.shape[1])
index_flat.add(review_embeddings)

# Hierarchical Navigable Small World (HNSW) index
index_hnsw = faiss.IndexHNSWFlat(review_embeddings.shape[1], 32)
index_hnsw.add(review_embeddings)

# Inverted File (IVF) index with Product Quantization (PQ)
nlist = 100  # Number of Voronoi cells
m = 8  # Number of subquantizers
bits = 8  # Number of bits per subquantizer
index_ivfpq = faiss.IndexIVFPQ(faiss.IndexFlatL2(review_embeddings.shape[1]), review_embeddings.shape[1], nlist, m, bits)
index_ivfpq.train(review_embeddings)
index_ivfpq.add(review_embeddings)

# Perform similarity search
query = "Hotel with a view of the Eiffel Tower"
query_embedding = model.encode([query]).astype('float32')
k = 15  # Number of similar reviews to retrieve

# Flat index search
start_time = time.time()
distances_flat, indices_flat = index_flat.search(query_embedding, k)
flat_search_time = time.time() - start_time
print(f"Flat index search time: {flat_search_time:.4f} seconds")

# HNSW index search
start_time = time.time()
distances_hnsw, indices_hnsw = index_hnsw.search(query_embedding, k)
hnsw_search_time = time.time() - start_time
print(f"HNSW index search time: {hnsw_search_time:.4f} seconds")

# IVF-PQ index search
start_time = time.time()
distances_ivfpq, indices_ivfpq = index_ivfpq.search(query_embedding, k)
ivfpq_search_time = time.time() - start_time
print(f"IVF-PQ index search time: {ivfpq_search_time:.4f} seconds")

Flat index search time: 0.0014 seconds
HNSW index search time: 0.0010 seconds
IVF-PQ index search time: 0.0006 seconds

In [ ]:
# Print the top-k similar reviews for each index
print(f"\nQuery: {query}")

print("\nTop similar reviews (Flat index):")
for i, idx in enumerate(indices_flat[0], 1):
    print(f"{i}. {df_paris.iloc[idx]['hotel_name']}")
    #print(f"{i}. {df_paris.iloc[idx]['review_text']}")

print("\nTop similar reviews (HNSW index):")
for i, idx in enumerate(indices_hnsw[0], 1):
    print(f"{i}. {df_paris.iloc[idx]['hotel_name']}")
    #print(f"{i}. {df_paris.iloc[idx]['review_text']}")

print("\nTop similar reviews (IVF-PQ index):")
for i, idx in enumerate(indices_ivfpq[0], 1):
    print(f"{i}. {df_paris.iloc[idx]['hotel_name']}")
    #print(f"{i}. {df_paris.iloc[idx]['review_text']}")

Query: Hotel with a view of the Eiffel Tower

Top similar reviews (Flat index):
1. Pullman Paris Eiffel Tower Hotel
2. Pullman Paris Eiffel Tower Hotel
3. Hotel Tourisme Avenue
4. Citadines Tour Eiffel Paris
5. Passy Eiffel Hotel
6. Hotel Marignan Champs-Elysees
7. Citadines Tour Eiffel Paris
8. Hotel Tourisme Avenue
9. Hotel Marignan Champs-Elysees
10. Passy Eiffel Hotel
11. Hotel La Comtesse
12. Cler Hotel
13. Citadines Tour Eiffel Paris
14. Pullman Paris Eiffel Tower Hotel
15. Pullman Paris Eiffel Tower Hotel

Top similar reviews (HNSW index):
1. Pullman Paris Eiffel Tower Hotel
2. Pullman Paris Eiffel Tower Hotel
3. Hotel Tourisme Avenue
4. Citadines Tour Eiffel Paris
5. Passy Eiffel Hotel
6. Hotel Marignan Champs-Elysees
7. Citadines Tour Eiffel Paris
8. Hotel Tourisme Avenue
9. Hotel Marignan Champs-Elysees
10. Passy Eiffel Hotel
11. Hotel La Comtesse
12. Cler Hotel
13. Citadines Tour Eiffel Paris
14. Pullman Paris Eiffel Tower Hotel
15. Pullman Paris Eiffel Tower Hotel

Top similar reviews (IVF-PQ index):
1. Pullman Paris Eiffel Tower Hotel
2. Hotel Marignan Champs-Elysees
3. Citadines Tour Eiffel Paris
4. Hotel Tourisme Avenue
5. Passy Eiffel Hotel
6. Passy Eiffel Hotel
7. Passy Eiffel Hotel
8. Cler Hotel
9. Hotel Marignan Champs-Elysees
10. Cler Hotel
11. Hotel La Comtesse
12. Passy Eiffel Hotel
13. Pullman Paris Eiffel Tower Hotel
14. Passy Eiffel Hotel
15. Cler Hotel

In [ ]:
# Count unique hotels surfaced by each index configuration.

# Print the top-k similar reviews for each index
print(f"\nQuery: {query}")

print("\nTop similar reviews (Flat index):")
flat_hotels = set()
for i, idx in enumerate(indices_flat[0], 1):
    hotel_name = df_paris.iloc[idx]['hotel_name']
    flat_hotels.add(hotel_name)
    print(f"{i}. {hotel_name}")
print(f"Number of unique hotels (Flat index): {len(flat_hotels)}")

print("\nTop similar reviews (HNSW index):")
hnsw_hotels = set()
for i, idx in enumerate(indices_hnsw[0], 1):
    hotel_name = df_paris.iloc[idx]['hotel_name']
    hnsw_hotels.add(hotel_name)
    print(f"{i}. {hotel_name}")
print(f"Number of unique hotels (HNSW index): {len(hnsw_hotels)}")

print("\nTop similar reviews (IVF-PQ index):")
ivfpq_hotels = set()
for i, idx in enumerate(indices_ivfpq[0], 1):
    hotel_name = df_paris.iloc[idx]['hotel_name']
    ivfpq_hotels.add(hotel_name)
    print(f"{i}. {hotel_name}")
print(f"Number of unique hotels (IVF-PQ index): {len(ivfpq_hotels)}")

Query: Hotel with a view of the Eiffel Tower

Top similar reviews (Flat index):
1. Pullman Paris Eiffel Tower Hotel
2. Pullman Paris Eiffel Tower Hotel
3. Hotel Tourisme Avenue
4. Citadines Tour Eiffel Paris
5. Passy Eiffel Hotel
6. Hotel Marignan Champs-Elysees
7. Citadines Tour Eiffel Paris
8. Hotel Tourisme Avenue
9. Hotel Marignan Champs-Elysees
10. Passy Eiffel Hotel
11. Hotel La Comtesse
12. Cler Hotel
13. Citadines Tour Eiffel Paris
14. Pullman Paris Eiffel Tower Hotel
15. Pullman Paris Eiffel Tower Hotel
Number of unique hotels (Flat index): 7

Top similar reviews (HNSW index):
1. Pullman Paris Eiffel Tower Hotel
2. Pullman Paris Eiffel Tower Hotel
3. Hotel Tourisme Avenue
4. Citadines Tour Eiffel Paris
5. Passy Eiffel Hotel
6. Hotel Marignan Champs-Elysees
7. Citadines Tour Eiffel Paris
8. Hotel Tourisme Avenue
9. Hotel Marignan Champs-Elysees
10. Passy Eiffel Hotel
11. Hotel La Comtesse
12. Cler Hotel
13. Citadines Tour Eiffel Paris
14. Pullman Paris Eiffel Tower Hotel
15. Pullman Paris Eiffel Tower Hotel
Number of unique hotels (HNSW index): 7

Top similar reviews (IVF-PQ index):
1. Pullman Paris Eiffel Tower Hotel
2. Hotel Marignan Champs-Elysees
3. Citadines Tour Eiffel Paris
4. Hotel Tourisme Avenue
5. Passy Eiffel Hotel
6. Passy Eiffel Hotel
7. Passy Eiffel Hotel
8. Cler Hotel
9. Hotel Marignan Champs-Elysees
10. Cler Hotel
11. Hotel La Comtesse
12. Passy Eiffel Hotel
13. Pullman Paris Eiffel Tower Hotel
14. Passy Eiffel Hotel
15. Cler Hotel
Number of unique hotels (IVF-PQ index): 7

## What's next

Chapter 5 plugs the **decoder** (LLM) on top of these retrievals to start producing grounded answers — the first half of a full RAG pipeline. Chapter 6 wires retrieval + generation together end-to-end and adds a real vector database (Qdrant).